//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptos
    {
        public int idconcepto { get; set; }
        public string grupo { get; set; }
        public string tipoconcepto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idunidad { get; set; }
        public Nullable<bool> inventario { get; set; }
        public string cvesat { get; set; }
        public int idorigen { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
