//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class contribuyentes
    {
        public int idcontribuyente { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string contacto { get; set; }
        public string movil { get; set; }
        public string domicilio { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
