//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosdigitales
    {
        public int iddocumentodigital { get; set; }
        public string tiposolicitud { get; set; }
        public Nullable<int> ejercicio { get; set; }
        public Nullable<int> periodo { get; set; }
        public string serie { get; set; }
        public string folio { get; set; }
        public string tipoxml { get; set; }
        public string uuid { get; set; }
        public string rfcemisor { get; set; }
        public string nombreemisor { get; set; }
        public string rfcreceptor { get; set; }
        public string nombrereceptor { get; set; }
        public string rfcpac { get; set; }
        public Nullable<System.DateTime> fechaemision { get; set; }
        public Nullable<System.DateTime> fechacertificacionsat { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> totaltrasladados { get; set; }
        public Nullable<decimal> totalretenidos { get; set; }
        public Nullable<decimal> totaltrasladadoslocales { get; set; }
        public Nullable<decimal> totalretenidoslocales { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string estatus { get; set; }
        public Nullable<System.DateTime> fechacancelacion { get; set; }
        public byte[] xml { get; set; }
        public string codigoestatus { get; set; }
        public string escancelable { get; set; }
        public string estatuscancelacion { get; set; }
        public string validacionefos { get; set; }
        public string clasificador { get; set; }
        public Nullable<int> id { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
