//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class valorpredial
    {
        public int idvalorcatastral { get; set; }
        public Nullable<decimal> limiteinferior { get; set; }
        public Nullable<decimal> limitesuperior { get; set; }
        public Nullable<decimal> cuotafijanual { get; set; }
        public Nullable<decimal> factorexcedentelimite { get; set; }
    }
}
