//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobropredial
    {
        public int idcobropredial { get; set; }
        public Nullable<int> idcontribuyente { get; set; }
        public Nullable<decimal> valorcatrastral { get; set; }
        public Nullable<decimal> limiteinferior { get; set; }
        public Nullable<decimal> factorexcedentelimite { get; set; }
        public Nullable<decimal> cuotafija { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
