//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosdigitalesconceptos
    {
        public int iddocumentodigitalconcepto { get; set; }
        public Nullable<int> iddocumentodigital { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string noidentificacion { get; set; }
        public string unidad { get; set; }
        public string claveunidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> valorunitario { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string claveprodserv { get; set; }
        public string destino01 { get; set; }
        public string destino02 { get; set; }
        public string destino03 { get; set; }
        public string destino04 { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
