//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos
    {
        public int idingreso { get; set; }
        public int idtipoingreso { get; set; }
        public string tipoingreso { get; set; }
        public string folio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idcontribuyente { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> idempleado { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
