//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametros
    {
        public int idparametro { get; set; }
        public string dirdefault { get; set; }
        public string dirbackup { get; set; }
        public string dirxml { get; set; }
        public string dirpdf { get; set; }
        public string dirinformes { get; set; }
        public string dirrecursoscfdi { get; set; }
        public string direxportaciones { get; set; }
        public string archivocer { get; set; }
        public string archivokey { get; set; }
        public string efirmapassword { get; set; }
        public string ciecpassword { get; set; }
        public string dirtmp { get; set; }
        public string dirpaquetes { get; set; }
        public string diropenssl { get; set; }
        public string presidente { get; set; }
        public string tesorero { get; set; }
        public string supervisor { get; set; }
        public string responsable { get; set; }
        public string leyenda1 { get; set; }
        public string leyenda2 { get; set; }
        public string leyenda3 { get; set; }
        public string leyenda4 { get; set; }
        public byte[] logoizquierdo { get; set; }
        public byte[] logoderecho { get; set; }
        public byte[] marcadeagua { get; set; }
        public Nullable<int> idformatosolicitud { get; set; }
        public Nullable<int> idformatopedido { get; set; }
        public Nullable<int> idformatoorden { get; set; }
        public Nullable<int> idformatogasolina { get; set; }
        public Nullable<int> idformatomantenimiento { get; set; }
        public Nullable<int> idformatoconstancia { get; set; }
        public Nullable<int> idformatoinforme { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
