//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudesdescargas
    {
        public int idsolicituddescarga { get; set; }
        public Nullable<System.DateTime> fechainicial { get; set; }
        public Nullable<System.DateTime> fechafinal { get; set; }
        public string rfcemisor { get; set; }
        public string rfcreceptor { get; set; }
        public string rfcsolicitante { get; set; }
        public string tiposolicitud { get; set; }
        public string idsolicitud { get; set; }
        public string estatus { get; set; }
        public string mensaje { get; set; }
        public string idpaquetes { get; set; }
        public string numerocfdis { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
