//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vconfdapempleados
    {
        public int idconfdapempleado { get; set; }
        public Nullable<int> idempleado { get; set; }
        public string nombrecompleto { get; set; }
        public Nullable<int> iddepartamento { get; set; }
        public string nombredepartamento { get; set; }
        public Nullable<int> idpuesto { get; set; }
        public string nombrepuesto { get; set; }
        public string estatus { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observaciones { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
