//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cipal_aaa010101aaa_municipio_de_meridaEntities : DbContext
    {
        public cipal_aaa010101aaa_municipio_de_meridaEntities()
            : base("name=cipal_aaa010101aaa_municipio_de_meridaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apoyos> apoyos { get; set; }
        public virtual DbSet<beneficiarios> beneficiarios { get; set; }
        public virtual DbSet<confdapempleados> confdapempleados { get; set; }
        public virtual DbSet<constancias> constancias { get; set; }
        public virtual DbSet<contribuyentes> contribuyentes { get; set; }
        public virtual DbSet<contribuyentesapocrifos> contribuyentesapocrifos { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<detapoyos> detapoyos { get; set; }
        public virtual DbSet<detconstancias> detconstancias { get; set; }
        public virtual DbSet<detgasolinas> detgasolinas { get; set; }
        public virtual DbSet<detinformes> detinformes { get; set; }
        public virtual DbSet<detmantenimientos> detmantenimientos { get; set; }
        public virtual DbSet<detordenes> detordenes { get; set; }
        public virtual DbSet<detsolicitudes> detsolicitudes { get; set; }
        public virtual DbSet<documentosdigitales> documentosdigitales { get; set; }
        public virtual DbSet<documentosdigitalesconceptos> documentosdigitalesconceptos { get; set; }
        public virtual DbSet<documentosdigitalesimpuestos> documentosdigitalesimpuestos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<formatos> formatos { get; set; }
        public virtual DbSet<gasolinas> gasolinas { get; set; }
        public virtual DbSet<impdetpedidos> impdetpedidos { get; set; }
        public virtual DbSet<informes> informes { get; set; }
        public virtual DbSet<inventarios> inventarios { get; set; }
        public virtual DbSet<mantenimientos> mantenimientos { get; set; }
        public virtual DbSet<movinventarios> movinventarios { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<parametros> parametros { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<puestos> puestos { get; set; }
        public virtual DbSet<seriesfoliacion> seriesfoliacion { get; set; }
        public virtual DbSet<solicitudes> solicitudes { get; set; }
        public virtual DbSet<solicitudesdescargas> solicitudesdescargas { get; set; }
        public virtual DbSet<tipoapoyos> tipoapoyos { get; set; }
        public virtual DbSet<tipoingresos> tipoingresos { get; set; }
        public virtual DbSet<vehiculos> vehiculos { get; set; }
        public virtual DbSet<cfdiformapago> cfdiformapago { get; set; }
        public virtual DbSet<cfditasaimpuesto> cfditasaimpuesto { get; set; }
        public virtual DbSet<cfditipojornada> cfditipojornada { get; set; }
        public virtual DbSet<cfditiponomina> cfditiponomina { get; set; }
        public virtual DbSet<cfditiporegimen> cfditiporegimen { get; set; }
        public virtual DbSet<cfditiporelacionfiscal> cfditiporelacionfiscal { get; set; }
        public virtual DbSet<cobropredial> cobropredial { get; set; }
        public virtual DbSet<valorpredial> valorpredial { get; set; }
        public virtual DbSet<vapoyos> vapoyos { get; set; }
        public virtual DbSet<vconfdapempleados> vconfdapempleados { get; set; }
        public virtual DbSet<vconstancias> vconstancias { get; set; }
        public virtual DbSet<vinformes> vinformes { get; set; }
        public virtual DbSet<vordenes> vordenes { get; set; }
        public virtual DbSet<vpedidos> vpedidos { get; set; }
        public virtual DbSet<vsolicitudes> vsolicitudes { get; set; }
        public virtual DbSet<ingresos> ingresos { get; set; }
        public virtual DbSet<vingresos> vingresos { get; set; }
        public virtual DbSet<vinventarios> vinventarios { get; set; }
        public virtual DbSet<vgasolinas> vgasolinas { get; set; }
        public virtual DbSet<vmantenimientos> vmantenimientos { get; set; }
        public virtual DbSet<conceptos> conceptos { get; set; }
        public virtual DbSet<impuestos> impuestos { get; set; }
        public virtual DbSet<unidades> unidades { get; set; }
        public virtual DbSet<detpedidos> detpedidos { get; set; }
    }
}
