//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cipal.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class seriesfoliacion
    {
        public int idseriefoliacion { get; set; }
        public string tiposerie { get; set; }
        public string serie { get; set; }
        public Nullable<int> inicial { get; set; }
        public Nullable<int> actual { get; set; }
        public Nullable<bool> vigente { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
